### ISSUE TITLE
cant run electrasmart-auth after pip install

### ISSUE THREAD

**Issue by xposionn** [yonatanp/electrasmart-custom-component#16]
cant run electrasmart-auth after pip install.

**Comment by yonatanp** [comment]
Hi @xposionn , were you able to resolve this issue? If not, could you share your log and error messages?
Usually these issues stem from general setup issues such as python path configuration.

**Comment by noamshn** [comment]
Hi Yonatan, this problem happens to me too. The error is "name 'electrasmart' is not defined".
Do you know how I can solve it?

**Comment by yonatanp** [comment]
Could you share the command and the full output?
(Masking credentials of course)

**Comment by noamshn** [comment]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-7a4e2016aa62> in <module>()
----> 1 electrasmart-auth

NameError: name 'electrasmart' is not defined

**Comment by yonatanp** [comment]
Something here is very wrong. It is as if you are trying to run the library name as a python script.
Could you provide the full command that you  used? A screenshot might help clarify the context.

**Comment by noamshn** [comment]
![IMG_20220126_214353](https://user-images.githubusercontent.com/51543044/151235719-9f696ac7-d5ff-4e99-930f-fa0a5c0212b2.jpg)

I added a photo. Im dont have any background in software so maybe I made a mistake.
I ran the code on google colab.

**Comment by cr-perry** [comment]
No worries! Your screenshot was very helpful, now I understand the full context.
What happens is that "electrasmart-auth" is a program to run from command line, not normally from within colab's python.

Here's what I suggest you try:
First, add an exclamation point before the "electrasmart-auth" command. This tells colab to run this as a normal command, not in python.
Second, the program takes your 10-digit phone number as parameter.

So instead of
```
[2] electrasmart-auth
```
try running e.g.
```
[2] !electrasmart-auth 0546667788
```
assuming that 054 6667788 is your phone number, *already* registered to electrsmart in their mobile app.

**Comment by yonatanp** [comment]
No worries! Your screenshot was very helpful, now I understand the full context.
What happens is that "electrasmart-auth" is a program to run from command line, not normally from within colab's python.

Here's what I suggest you try:
First, add an exclamation point before the "electrasmart-auth" command. This tells colab to run this as a normal command, not in python.
Second, the program takes your 10-digit phone number as parameter.

So instead of
```
[2] electrasmart-auth
```
try running e.g.
```
[2] !electrasmart-auth 0546667788
```
assuming that 054 6667788 is your phone number, *already* registered to electrsmart in their mobile app.

**Comment by noamshn** [comment]
Thank you very much, it worked! :)
